kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "webapp"
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: app-config
      initContainers:
      - name: check-db-ready
        image: centos/postgresql-10-centos7
        command: ['sh', '-c', "-i",
          'until pg_isready -h postgres -p 5432; 
          do echo waiting for database; sleep 2; done;']

      containers:
      - name: webapp
        image: 172.30.1.1:5000/sandbox/webapp:latest
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_FILE
          value: /etc/config/config.yaml
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: password
        - name: POSTGRES_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: admin_password
  replicas: 1
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "webapp"
        from:
          kind: "ImageStreamTag"
          name: "webapp:latest"
  strategy: 
    type: "Rolling"
  paused: false 
  revisionHistoryLimit: 5 
  minReadySeconds: 0